loki:
  serviceAccount:
    create: false

  isDefault: true
  url: http://{{(include "loki.serviceName" .)}}:{{ .Values.loki.service.port }}

  config:
    schema_config:
      configs:
        - from: 2022-01-11
          store: boltdb-shipper
          object_store: aws
          schema: v12
          index:
            period: 24h
            prefix: index_
    storage_config:
      aws:
        s3: s3://region/bucket-name
        region: region
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: s3
      filesystem:
        directory: /data/loki/chunks
  
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  datasources:
    - name: Loki
      type: loki
      url: http://loki:3100
      jsonData:
        maxLines: 1000
        derivedFields:
          - matcherRegex: "traceID=(\\w+)"
            name: traceID
            url: '$${__value.raw}'
      uid: my_jaeger_uid   

promtail:
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://{{ .Release.Name }}:3100/loki/api/v1/push